export const projects = [
  {
    id: 'weather-app',
    title: 'Weather Application',
    description: 'A real-time weather app that displays current conditions and forecasts',
    shortDescription: 'Real-time weather forecast app',
    technologies: ['React', 'API Integration', 'Tailwind CSS'],
    image: 'https://via.placeholder.com/400x300?text=Weather+App',
    overview: 'A responsive weather application built with React that fetches real-time weather data from an external API.',
    problem: 'Users need a fast, intuitive way to check weather conditions without ads or unnecessary clutter.',
    solution: 'Created a clean, minimalist interface showing current weather, hourly and daily forecasts with location search.',
    challenges: 'Handling API rate limits, managing loading states, ensuring responsive design across devices.',
    learnings: 'Gained experience with async/await, API integration, and state management in React.',
    githubUrl: 'https://github.com/yourusername/weather-app',
    liveUrl: 'https://weather-app-demo.com',
  },
  {
    id: 'todo-list',
    title: 'Todo List Manager',
    description: 'Task management app with local storage persistence',
    shortDescription: 'Full-featured todo application',
    technologies: ['JavaScript', 'LocalStorage', 'HTML/CSS'],
    image: 'https://via.placeholder.com/400x300?text=Todo+List',
    overview: 'A simple but powerful todo list application that persists data locally.',
    problem: 'Need a quick, offline-available way to manage daily tasks.',
    solution: 'Built a lightweight app with add, delete, edit, and filter features using localStorage.',
    challenges: 'Data persistence, handling edge cases, intuitive UI design.',
    learnings: 'Learned about DOM manipulation, event handling, and browser storage APIs.',
    githubUrl: 'https://github.com/yourusername/todo-list',
    liveUrl: 'https://todo-app-demo.com',
  },
  {
    id: 'portfolio-site',
    title: 'Personal Portfolio',
    description: 'A modern portfolio site showcasing projects and skills',
    shortDescription: 'Next.js portfolio with Tailwind CSS',
    technologies: ['Next.js', 'Tailwind CSS', 'React'],
    image: 'https://via.placeholder.com/400x300?text=Portfolio',
    overview: 'This portfolio website built with Next.js to showcase all academic projects.',
    problem: 'Need a professional way to present projects to recruiters and peers.',
    solution: 'Created a responsive portfolio with project showcase, about section, and contact info.',
    challenges: 'Design consistency, performance optimization, GitHub Pages deployment.',
    learnings: 'Mastered Next.js basics, Tailwind CSS styling, and static site generation.',
    githubUrl: 'https://github.com/yourusername/portfolio',
    liveUrl: 'https://yourportfolio.com',
  },
  {
    id: 'calculator',
    title: 'Advanced Calculator',
    description: 'Scientific calculator with complex mathematical functions',
    shortDescription: 'Feature-rich scientific calculator',
    technologies: ['JavaScript', 'Math.js', 'CSS Grid'],
    image: 'https://via.placeholder.com/400x300?text=Calculator',
    overview: 'A scientific calculator supporting basic operations and advanced functions.',
    problem: 'Standard calculators lack advanced mathematical operations needed for complex calculations.',
    solution: 'Developed calculator with trigonometric, logarithmic, and exponential functions.',
    challenges: 'Parsing mathematical expressions, handling precision issues, responsive button layout.',
    learnings: 'Expression parsing, error handling, CSS Grid layout techniques.',
    githubUrl: 'https://github.com/yourusername/calculator',
    liveUrl: 'https://calculator-demo.com',
  },
  {
    id: 'habit-tracker',
    title: 'Habit Tracker',
    description: 'App to build and track daily habits with visual progress',
    shortDescription: 'Habit building and tracking tool',
    technologies: ['React', 'Charts.js', 'LocalStorage'],
    image: 'https://via.placeholder.com/400x300?text=Habit+Tracker',
    overview: 'Track daily habits and visualize progress over time with charts.',
    problem: 'Building habits is difficult without visual tracking and motivation.',
    solution: 'Created an app with habit logging, streak tracking, and progress visualization.',
    challenges: 'Date management, chart rendering, persistent data across sessions.',
    learnings: 'Data visualization, working with dates, handling large datasets.',
    githubUrl: 'https://github.com/yourusername/habit-tracker',
    liveUrl: 'https://habit-tracker-demo.com',
  },
  {
    id: 'recipe-finder',
    title: 'Recipe Finder',
    description: 'Search and discover recipes with dietary filters',
    shortDescription: 'Recipe discovery and search app',
    technologies: ['React', 'REST API', 'Axios'],
    image: 'https://via.placeholder.com/400x300?text=Recipe+Finder',
    overview: 'Search for recipes based on ingredients and dietary preferences.',
    problem: 'Finding recipes that match specific ingredients and diet requirements is tedious.',
    solution: 'Integrated with recipe API to provide filtered search and detailed recipe views.',
    challenges: 'API integration, handling complex filtering, displaying recipe details.',
    learnings: 'API consumption, filtering algorithms, detailed UI design for content.',
    githubUrl: 'https://github.com/yourusername/recipe-finder',
    liveUrl: 'https://recipe-finder-demo.com',
  },
  {
    id: 'music-player',
    title: 'Music Player',
    description: 'Web-based audio player with playlist management',
    shortDescription: 'Feature-complete music player',
    technologies: ['HTML5 Audio', 'JavaScript', 'CSS Animations'],
    image: 'https://via.placeholder.com/400x300?text=Music+Player',
    overview: 'A sleek music player with playlist support and playback controls.',
    problem: 'Need an elegant, browser-based solution for playing audio with playlists.',
    solution: 'Built player with HTML5 audio API, custom controls, and playlist management.',
    challenges: 'Audio API quirks, progress bar sync, UI animations.',
    learnings: 'HTML5 Media API, progress tracking, smooth animations.',
    githubUrl: 'https://github.com/yourusername/music-player',
    liveUrl: 'https://music-player-demo.com',
  },
  {
    id: 'expense-tracker',
    title: 'Expense Tracker',
    description: 'Personal finance tracker with budget management',
    shortDescription: 'Budget and expense management app',
    technologies: ['React', 'Context API', 'Chart.js'],
    image: 'https://via.placeholder.com/400x300?text=Expense+Tracker',
    overview: 'Track expenses, set budgets, and visualize spending patterns.',
    problem: 'People struggle to track spending and stay within budget.',
    solution: 'Created app with transaction logging, budget alerts, and spending analytics.',
    challenges: 'Complex state management, accurate calculations, mobile responsiveness.',
    learnings: 'Context API, financial calculations, mobile-first design.',
    githubUrl: 'https://github.com/yourusername/expense-tracker',
    liveUrl: 'https://expense-tracker-demo.com',
  },
  {
    id: 'chat-app',
    title: 'Real-time Chat Application',
    description: 'Web socket-based messaging app with user authentication',
    shortDescription: 'Real-time messaging application',
    technologies: ['Node.js', 'Socket.io', 'React', 'MongoDB'],
    image: 'https://via.placeholder.com/400x300?text=Chat+App',
    overview: 'A real-time chat application enabling instant messaging between users.',
    problem: 'Need a simple, real-time communication platform for group messaging.',
    solution: 'Built with WebSockets for instant messaging, user auth, and message history.',
    challenges: 'Real-time synchronization, scalability, user authentication.',
    learnings: 'WebSockets, backend with Node.js, real-time data management.',
    githubUrl: 'https://github.com/yourusername/chat-app',
    liveUrl: 'https://chat-app-demo.com',
  },
  {
    id: 'image-gallery',
    title: 'Image Gallery',
    description: 'Responsive image gallery with lazy loading',
    shortDescription: 'Modern image gallery with effects',
    technologies: ['React', 'Lazy Loading', 'CSS'],
    image: 'https://via.placeholder.com/400x300?text=Image+Gallery',
    overview: 'A beautiful, performant image gallery with lazy loading.',
    problem: 'Large image galleries load slowly and have poor user experience.',
    solution: 'Implemented lazy loading, optimized images, and smooth transitions.',
    challenges: 'Performance optimization, lazy loading implementation, responsive design.',
    learnings: 'Performance optimization, image handling, intersection observer API.',
    githubUrl: 'https://github.com/yourusername/image-gallery',
    liveUrl: 'https://image-gallery-demo.com',
  },
  {
    id: 'blog-cms',
    title: 'Blog CMS',
    description: 'Markdown-based blog with comment system',
    shortDescription: 'Markdown blog with comments',
    technologies: ['Next.js', 'Markdown', 'PostgreSQL'],
    image: 'https://via.placeholder.com/400x300?text=Blog+CMS',
    overview: 'A lightweight blog CMS supporting markdown and comments.',
    problem: 'Existing blogging platforms are bloated and difficult to customize.',
    solution: 'Built minimal CMS with markdown parsing and comment functionality.',
    challenges: 'Markdown parsing, comment moderation, content management.',
    learnings: 'Markdown processing, database design, content management systems.',
    githubUrl: 'https://github.com/yourusername/blog-cms',
    liveUrl: 'https://blog-demo.com',
  },
]
